# Generated by Django 3.1.3 on 2021-05-06 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Loan'), (2, 'Return')], default=1)),
                ('date', models.DateField()),
                ('loan_id', models.IntegerField(blank=True, null=True)),
                ('books', models.ManyToManyField(related_name='book_movement_set', related_query_name='book', to='book.Book', verbose_name='book_movement')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
